apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: arjunmusic143/task-app:frontendapp1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: frontend
  name: react-deployment
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: react
  type: LoadBalancer