apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app.kubernetes.io/name: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: pritamkhergade/tomcat:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tom-conf
          mountPath: /usr/local/tomcat/conf/context.xml
      volumes:
        - name: tom-conf
          configMap:
            name: tom-conf


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: proxy
  name: tomcat-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat
  type: LoadBalancer